Get the Suburb Name, Postcode, State, Latitude and Longitude from [opendatasoft](https://public.opendatasoft.com/explore/dataset/georef-australia-state-suburb/export/?disjunctive.ste_code&disjunctive.ste_name&disjunctive.lga_code&disjunctive.lga_name&disjunctive.scc_code&disjunctive.scc_name&location=4,-27.83417,132.40691&basemap=jawg.light&dataChart=eyJxdWVyaWVzIjpbeyJjb25maWciOnsiZGF0YXNldCI6Imdlb3JlZi1hdXN0cmFsaWEtc3RhdGUtc3VidXJiIiwib3B0aW9ucyI6eyJkaXNqdW5jdGl2ZS5zdGVfY29kZSI6dHJ1ZSwiZGlzanVuY3RpdmUuc3RlX25hbWUiOnRydWUsImRpc2p1bmN0aXZlLmxnYV9jb2RlIjp0cnVlLCJkaXNqdW5jdGl2ZS5sZ2FfbmFtZSI6dHJ1ZSwiZGlzanVuY3RpdmUuc2NjX2NvZGUiOnRydWUsImRpc2p1bmN0aXZlLnNjY19uYW1lIjp0cnVlLCJsb2NhdGlvbiI6IjQsLTI3LjgzNDE3LDEzMi40MDY5MSIsImJhc2VtYXAiOiJqYXdnLmxpZ2h0In19LCJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IkNPVU5UIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI0ZGNTE1QSJ9XSwieEF4aXMiOiJ5ZWFyIiwibWF4cG9pbnRzIjoiIiwidGltZXNjYWxlIjoieWVhciIsInNvcnQiOiIifV0sImRpc3BsYXlMZWdlbmQiOnRydWUsImFsaWduTW9udGgiOnRydWV9)

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("../Datasets/georef-australia-state-suburb.csv", delimiter=';')

In [2]:
df.head()

,Geo Point,Geo Shape,Year,Official Code State,Official Name State,Official Code Local Government Area,Official Name Local Government Area,Official Code Suburb,Official Name Suburb,Iso 3166-3 Area Code,Type
0,"-36.01193158762528, 148.786320441595","{""coordinates"": [[[148.71675360000006, -36.060...",2021,1,New South Wales,17040,Snowy Monaro Regional,10015,Adaminaby,AUS,suburb
1,"-36.07369799464406, 146.91346780765934","{""coordinates"": [[[146.92431042300007, -36.086...",2021,1,New South Wales,10050,Albury,10027,Albury,AUS,suburb
2,"-32.91425516102453, 148.26802074020546","{""coordinates"": [[[148.19998799900006, -32.966...",2021,1,New South Wales,16200,Parkes,10029,Alectown,AUS,suburb
3,"-34.40869358826243, 150.53677066431447","{""coordinates"": [[[150.5122384670001, -34.4223...",2021,1,New South Wales,18350,Wingecarribee,10044,Alpine,AUS,suburb
4,"-34.91797895821861, 145.6572484339588","{""coordinates"": [[[145.66848513900004, -35.017...",2021,1,New South Wales,15560,Murrumbidgee,10081,Argoon,AUS,suburb

In [3]:
# 1 missing value from geo point
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15334 entries, 0 to 15333
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Geo Point                            15333 non-null  object
 1   Geo Shape                            15333 non-null  object
 2   Year                                 15334 non-null  int64
 3   Official Code State                  15334 non-null  object
 4   Official Name State                  15334 non-null  object
 5   Official Code Local Government Area  15334 non-null  object
 6   Official Name Local Government Area  15334 non-null  object
 7   Official Code Suburb                 15334 non-null  int64
 8   Official Name Suburb                 15334 non-null  object
 9   Iso 3166-3 Area Code                 15334 non-null  object
 10  Type                                 15334 non-null  object
dtypes: int64(2), object(9)
memory usage: 1.3+ MB

In [7]:
# Remove whitespace from the columns name
df.columns = df.columns.str.replace(' ', '')

In [8]:
df[df["GeoPoint"].isna()]

Empty DataFrame
Columns: [GeoPoint, GeoShape, Year, OfficialCodeState, OfficialNameState, OfficialCodeLocalGovernmentArea, OfficialNameLocalGovernmentArea, OfficialCodeSuburb, OfficialNameSuburb, Iso3166-3AreaCode, Type]
Index: []

In [9]:
# One row with a missing value. We can drop this
df = df.dropna()

In [12]:
df.groupby("OfficialNameState").count()

,GeoPoint,GeoShape,Year,OfficialCodeState,OfficialCodeLocalGovernmentArea,OfficialNameLocalGovernmentArea,OfficialCodeSuburb,OfficialNameSuburb,Iso3166-3AreaCode,Type
OfficialNameState,,,,,,,,,,
Australian Capital Territory,136,136,136,136,136,136,136,136,136,136
"Australian Capital Territory,New South Wales",4,4,4,4,4,4,4,4,4,4
New South Wales,4525,4525,4525,4525,4525,4525,4525,4525,4525,4525
"New South Wales,Queensland",7,7,7,7,7,7,7,7,7,7
"New South Wales,South Australia",2,2,2,2,2,2,2,2,2,2
"New South Wales,Victoria",9,9,9,9,9,9,9,9,9,9
Northern Territory,302,302,302,302,302,302,302,302,302,302
"Northern Territory,Queensland",2,2,2,2,2,2,2,2,2,2
"Northern Territory,South Australia,Western Australia",1,1,1,1,1,1,1,1,1,1
"Northern Territory,Western Australia",3,3,3,3,3,3,3,3,3,3
Other Territories,5,5,5,5,5,5,5,5,5,5
Queensland,3229,3229,3229,3229,3229,3229,3229,3229,3229,3229
South Australia,1692,1692,1692,1692,1692,1692,1692,1692,1692,1692
"South Australia,Victoria",3,3,3,3,3,3,3,3,3,3
"South Australia,Western Australia",1,1,1,1,1,1,1,1,1,1
Tasmania,775,775,775,775,775,775,775,775,775,775
Victoria,2940,2940,2940,2940,2940,2940,2940,2940,2940,2940
Western Australia,1697,1697,1697,1697,1697,1697,1697,1697,1697,1697

In [6]:
cord = df["Geo Point"].str.split(',').to_list()
cord = np.array(cord, dtype=float)

In [7]:
df["Latitude"] = cord[:, 0]
df["Longitude"] = cord[:, 1]

In [8]:
df.head()

,Geo Point,Geo Shape,Year,Official Code State,Official Name State,Official Code Local Government Area,Official Name Local Government Area,Official Code Suburb,Official Name Suburb,Iso 3166-3 Area Code,Type,Latitude,Longitude
0,"-36.01193158762528, 148.786320441595","{""coordinates"": [[[148.71675360000006, -36.060...",2021,1,New South Wales,17040,Snowy Monaro Regional,10015,Adaminaby,AUS,suburb,-36.011932,148.786320
1,"-36.07369799464406, 146.91346780765934","{""coordinates"": [[[146.92431042300007, -36.086...",2021,1,New South Wales,10050,Albury,10027,Albury,AUS,suburb,-36.073698,146.913468
2,"-32.91425516102453, 148.26802074020546","{""coordinates"": [[[148.19998799900006, -32.966...",2021,1,New South Wales,16200,Parkes,10029,Alectown,AUS,suburb,-32.914255,148.268021
3,"-34.40869358826243, 150.53677066431447","{""coordinates"": [[[150.5122384670001, -34.4223...",2021,1,New South Wales,18350,Wingecarribee,10044,Alpine,AUS,suburb,-34.408694,150.536771
4,"-34.91797895821861, 145.6572484339588","{""coordinates"": [[[145.66848513900004, -35.017...",2021,1,New South Wales,15560,Murrumbidgee,10081,Argoon,AUS,suburb,-34.917979,145.657248

In [9]:
df_out = df.loc[:, ["Official Name Suburb", "Official Name State", "Official Code Local Government Area",
            "Official Code State", "Latitude", "Longitude", "Geo Shape"]]
df_out.columns = df_out.columns.str.replace(' ', '')

In [10]:
df_out.to_csv("../Datasets/Suburb.csv", index=False)